name: Cache-Clean

on:
  workflow_dispatch:

permissions: write-all

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  auto_clean:
    runs-on: ubuntu-22.04
    steps:
      - name: Cache Clean
        run: gh cache delete --all
